# Basic Config

substitutions:
  #   # https://esphome.io/guides/configuration-types.html#substitutions
  #device_name: navien-heater # hostname & entity_id
  #friendly_name: "Navien Gas Heater" # Displayed in HA frontend
  project_name: Navien.esp8266
  project_version: "1.0.0"

packages:
  navien: !include navien-base.yml

logger:
#  level: VERBOSE #makes uart stream available in esphome logstream
  baud_rate: 0 #disable logging over uart to avoid interference
               # with sending/receiving over the UART port on ESP8266

  hardware_uart: UART1 # redirect logs to UART1 GPIO2 to avoid conflicts
                       # with the MCU communication through the main hardware UART

  # https://esphome.io/components/logger
  level: INFO
  esp8266_store_log_strings_in_flash: false
  

button:
  - platform: navien
    id: rs485_hot_button
    name: "Hot Button"
