climate:
  - platform: navien
    navien: navien_main
    id: navien_climate
    visual:
      min_temperature: 98F
      max_temperature: 120F
      temperature_step: '1Â°F'
    name: "${friendly_name} DHW Set Temperature"
